# SPRING
spring:
  application:
    name: shortener-api
  profiles:
    active: shortener-api

# SPRING DATA
  jpa:
    open-in-view: false
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        use_sql_comments: false
        format_sql: true
        jdbc.batch_size: 50
        order_inserts: true
        order_updates: true
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/postgres?createDatabaseIfNotExist=true
    username: postgre
    password: postgrepwd
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      platform: postgres

# REDIS
  redis:
    host: localhost
    port: 6379

# JACKSON
  jackson:
    serialization:
      INDENT_OUTPUT: true
    date-format: com.fasterxml.jackson.databind.util.StdDateFormat
    default-property-inclusion: non_null
  mvc:
    throw-exception-if-no-handler-found: true

# SPRING CLOUD
  cloud:
    loadbalancer:
    ribbon:
    enabled: false

retry-config:
  initial-interval-ms: 1000
  max-interval-ms: 10000
  multiplier: 2.0
  maxAttempts: 3
  sleep-time-ms: 2000

# SWAGGER
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

# METRICS
management:
  endpoints:
    web:
      base-path: /actuator
      exposure.include: health, prometheus
      path-mapping.prometheus: metrics
  endpoint:
    health:
      show-details: always
    prometheus:
      cache.time-to-live: 1ms